# Generated by Django 4.1.3 on 2022-11-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('B', 'Bahrain'), ('D', 'Dubai'), ('S', 'Saudi Arabia'), ('Q', 'Qatar'), ('K', 'Kuwait')], default='B', max_length=1)),
                ('popfigure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.popfigure')),
            ],
        ),
    ]
