# Generated by Django 4.1.3 on 2022-11-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_popfigure_image_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popfigure',
            name='image',
        ),
    ]
