# Generated by Django 4.1.3 on 2022-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_popfigure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popfigure',
            name='image',
            field=models.ImageField(default='image not found', upload_to='images'),
            preserve_default=False,
        ),
    ]
