# Generated by Django 4.1.3 on 2022-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_popfigure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popfigure',
            name='image',
            field=models.CharField(default='image not available', max_length=800),
        ),
    ]
